### ISSUE TITLE
Hylas Roadmap

### ISSUE THREAD

**Issue by lolligun** [lolligun/ModBahuang#2]
目前的实现方案是 Patch `ResMgr.Load` 后进行图片替换，然而这种方式实际上限制很大，而且必须要处理各个不同种类 GameObject 的布局。或许可以把整个 GameObject 直接从外部加载进来，但这又会导致每个资源都需要用 Unity Editor 来生成。
目前可以修改的部分以及所在的路径如下：
- [x] 人物立绘 (Game/Portrait/) `ResMgr.Load` ~~(背饰可能在其他地方)~~ 背饰在 \Back
- [x] 战斗小人 (Battle/Human/) `ResMgr.Load` Landed in https://github.com/lolligun/ModBahuang/commit/6f3df31943ff862ef962a1f884de703c680b44f3
- [ ] 怪物 (Battle/Monst/)
- [ ] 地图单位(坐骑/格子图标等) (Map/*)
- [ ] UI 图片 (UI/*) `ResMgr.Load<T>`
- [ ] 特效 (Effect/*)
    - [x] 双修图 (Effect/UI/Shuangxiu) Landed in e93275659d8d0f5ae6e7da12491e50589a010ca7
    - [x] 其他 UI (Effect/UI/*) Addressed in #23 
- [ ] 其他材质(突破/奇遇的图片等) (Texture/*)
    - [x] 奇遇 (Texture/Fortuitous/*) Addressed in #23 
    - [x] 背景 (Texture/BG/*) Addressed in #23 
- [ ] 声音 (Sound/*)

以及可能会有趣的额外部分：
- [ ] 加载动图
- [ ] 播放视频
- [ ] 对话语音

**Comment by lolligun** [comment]
关闭。请使用补天 (https://github.com/LangYueMc/Butian)
